<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  <PackageId>HttpMetrics</PackageId>
  <Version>1.0.0</Version>
  <Authors>saurav</Authors>
  <Description>Lightweight HTTP metrics library for .NET applications.</Description>
  <PackageTags>metrics;http;logging;performance</PackageTags>
  <RepositoryUrl>https://github.com/saurav7036/HttpMetrics</RepositoryUrl>
  <PackageLicenseExpression>MIT</PackageLicenseExpression>
  <PackageProjectUrl>https://github.com/saurav7036/HttpMetrics</PackageProjectUrl>
  <IncludeSymbols>true</IncludeSymbols>
  <IncludeSource>true</IncludeSource>
  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.ApplicationLoadBalancerEvents" Version="2.2.0" />
    <PackageReference Include="OpenTelemetry" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
  </ItemGroup>

</Project>
